In [5]:
n_tokens = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
max_gen_tokens = [100, 200, 400, 600]
neighbor_dist = [1, 2, 4, 8, 16, 20, 25, 32, 42, 52, 64, 70]
subset_size = [50, 100, 200, 400, 500, 800, 1000]
max_neighbors = [5, 10, 15, 20, 25, 30, 40]

exps = ['n_tokens', 'neighbor_dist', 'max_neighbors'] # max_neighbors, max_gen_tokens, subset_size]
exps = {exp: eval(exp) for exp in exps}

results_files = {}

In [6]:
import os
import re
import glob
import pandas as pd

# Directory paths
job_id = '67903336'
terminal_runs_dir = f'/home/liranc6/W25/adversarial-attacks-on-deep-learning/project/terminal_runs/{job_id}'

# Build the experiment command mapping
exp_commands = []
for exp_name, values in exps.items():
    for value in values:
        exp_commands.append((exp_name, value))

# Repeat the pattern 4 times (indices 0-107)
exp_commands = exp_commands * 4

# Function to extract result file path from output file
def extract_result_path(output_file):
    """Extract the result file path from a terminal output file"""
    try:
        with open(output_file, 'r') as f:
            content = f.read()
            # Look for the JSON file path
            match = re.search(r'(comprehensive_results/subset_size-1000/[^\s]+/all_experiment_results\.json)', content)
            if match:
                return match.group(1)
    except Exception as e:
        print(f"Error reading {output_file}: {e}")
    return None

# Scrape all output files
output_files = sorted(glob.glob(f"{terminal_runs_dir}/out_job_*.txt"))

# Build the DataFrame
rows = []
for idx, output_file in enumerate(output_files):
    if idx >= len(exp_commands):
        break
    
    exp_name, exp_value = exp_commands[idx]
    result_path = extract_result_path(output_file)
    
    if result_path:
        rows.append({
            'parameter_name': exp_name,
            'val': exp_value,
            'job_idx': idx,
            'path_to_all_results': result_path
        })

# Create DataFrame
results_df = pd.DataFrame(rows)

# Set pandas to display full column width
pd.set_option('display.max_colwidth', None)

print(f"Found {len(results_df)} results")
results_df

Found 107 results

,parameter_name,val,job_idx,path_to_all_results
0,n_tokens,0.1,0,comprehensive_results/subset_size-1000/2025-11-20_11-14/top_k_20_k_neighbors_15_n_tokens_0.1_MNT_300_test_size_0.2_reph_False_2025-11-20_11-14/all_experiment_results.json
1,n_tokens,0.2,1,comprehensive_results/subset_size-1000/2025-11-20_11-14/top_k_20_k_neighbors_15_n_tokens_0.2_MNT_300_test_size_0.2_reph_False_2025-11-20_11-14/all_experiment_results.json
2,n_tokens,0.3,2,comprehensive_results/subset_size-1000/2025-11-20_21-50/top_k_4_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-20_21-50/all_experiment_results.json
3,n_tokens,0.4,3,comprehensive_results/subset_size-1000/2025-11-22_03-17/top_k_70_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_03-17/all_experiment_results.json
4,n_tokens,0.5,4,comprehensive_results/subset_size-1000/2025-11-22_03-23/top_k_20_k_neighbors_5_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_03-23/all_experiment_results.json
...,...,...,...,...
102,max_neighbors,10.0,102,comprehensive_results/subset_size-1000/2025-11-22_03-00/top_k_25_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_03-00/all_experiment_results.json
103,max_neighbors,15.0,103,comprehensive_results/subset_size-1000/2025-11-22_03-08/top_k_32_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_03-08/all_experiment_results.json
104,max_neighbors,20.0,104,comprehensive_results/subset_size-1000/2025-11-22_03-10/top_k_42_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_03-10/all_experiment_results.json
105,max_neighbors,25.0,105,comprehensive_results/subset_size-1000/2025-11-22_03-11/top_k_52_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_03-11/all_experiment_results.json
106,max_neighbors,30.0,106,comprehensive_results/subset_size-1000/2025-11-22_03-14/top_k_64_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_03-14/all_experiment_results.json

In [7]:
# Access specific experiments using query
# Example: results_df[results_df['parameter_name'] == 'n_tokens']
results_df[results_df['parameter_name'] == 'n_tokens']

,parameter_name,val,job_idx,path_to_all_results
0,n_tokens,0.1,0,comprehensive_results/subset_size-1000/2025-11-20_11-14/top_k_20_k_neighbors_15_n_tokens_0.1_MNT_300_test_size_0.2_reph_False_2025-11-20_11-14/all_experiment_results.json
1,n_tokens,0.2,1,comprehensive_results/subset_size-1000/2025-11-20_11-14/top_k_20_k_neighbors_15_n_tokens_0.2_MNT_300_test_size_0.2_reph_False_2025-11-20_11-14/all_experiment_results.json
2,n_tokens,0.3,2,comprehensive_results/subset_size-1000/2025-11-20_21-50/top_k_4_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-20_21-50/all_experiment_results.json
3,n_tokens,0.4,3,comprehensive_results/subset_size-1000/2025-11-22_03-17/top_k_70_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_03-17/all_experiment_results.json
4,n_tokens,0.5,4,comprehensive_results/subset_size-1000/2025-11-22_03-23/top_k_20_k_neighbors_5_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_03-23/all_experiment_results.json
5,n_tokens,0.6,5,comprehensive_results/subset_size-1000/2025-11-22_03-23/top_k_20_k_neighbors_10_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_03-23/all_experiment_results.json
6,n_tokens,0.7,6,comprehensive_results/subset_size-1000/2025-11-22_03-28/top_k_20_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_03-28/all_experiment_results.json
7,n_tokens,0.8,7,comprehensive_results/subset_size-1000/2025-11-22_03-28/top_k_20_k_neighbors_20_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_03-28/all_experiment_results.json
27,n_tokens,0.1,27,comprehensive_results/subset_size-1000/2025-11-21_15-36/top_k_20_k_neighbors_15_n_tokens_0.1_MNT_300_test_size_0.2_reph_False_2025-11-21_15-36/all_experiment_results.json
28,n_tokens,0.2,28,comprehensive_results/subset_size-1000/2025-11-21_15-58/top_k_20_k_neighbors_15_n_tokens_0.2_MNT_300_test_size_0.2_reph_False_2025-11-21_15-58/all_experiment_results.json
29,n_tokens,0.3,29,comprehensive_results/subset_size-1000/2025-11-21_16-21/top_k_20_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-21_16-21/all_experiment_results.json
30,n_tokens,0.4,30,comprehensive_results/subset_size-1000/2025-11-20_11-14/top_k_20_k_neighbors_15_n_tokens_0.4_MNT_300_test_size_0.2_reph_False_2025-11-20_11-14/all_experiment_results.json
31,n_tokens,0.5,31,comprehensive_results/subset_size-1000/2025-11-21_16-42/top_k_20_k_neighbors_15_n_tokens_0.4_MNT_300_test_size_0.2_reph_False_2025-11-21_16-42/all_experiment_results.json
32,n_tokens,0.6,32,comprehensive_results/subset_size-1000/2025-11-21_17-02/top_k_20_k_neighbors_15_n_tokens_0.5_MNT_300_test_size_0.2_reph_False_2025-11-21_17-02/all_experiment_results.json
33,n_tokens,0.7,33,comprehensive_results/subset_size-1000/2025-11-21_17-23/top_k_20_k_neighbors_15_n_tokens_0.6_MNT_300_test_size_0.2_reph_False_2025-11-21_17-23/all_experiment_results.json
34,n_tokens,0.8,34,comprehensive_results/subset_size-1000/2025-11-21_17-33/top_k_20_k_neighbors_15_n_tokens_0.7_MNT_300_test_size_0.2_reph_False_2025-11-21_17-33/all_experiment_results.json
54,n_tokens,0.1,54,comprehensive_results/subset_size-1000/2025-11-21_23-00/top_k_20_k_neighbors_25_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-21_23-00/all_experiment_results.json
55,n_tokens,0.2,55,comprehensive_results/subset_size-1000/2025-11-21_23-02/top_k_20_k_neighbors_30_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-21_23-02/all_experiment_results.json
56,n_tokens,0.3,56,comprehensive_results/subset_size-1000/2025-11-21_23-20/top_k_20_k_neighbors_40_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-21_23-20/all_experiment_results.json
57,n_tokens,0.4,57,comprehensive_results/subset_size-1000/2025-11-21_23-23/top_k_20_k_neighbors_15_n_tokens_0.1_MNT_300_test_size_0.2_reph_False_2025-11-21_23-23/all_experiment_results.json
58,n_tokens,0.5,58,comprehensive_results/subset_size-1000/2025-11-21_23-44/top_k_20_k_neighbors_15_n_tokens_0.2_MNT_300_test_size_0.2_reph_False_2025-11-21_23-44/all_experiment_results.json
59,n_tokens,0.6,59,comprehensive_results/subset_size-1000/2025-11-21_23-44/top_k_20_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-21_23-44/all_experiment_results.json
60,n_tokens,0.7,60,comprehensive_results/subset_size-1000/2025-11-22_00-05/top_k_20_k_neighbors_15_n_tokens_0.4_MNT_300_test_size_0.2_reph_False_2025-11-22_00-05/all_experiment_results.json
61,n_tokens,0.8,61,comprehensive_results/subset_size-1000/2025-11-22_00-08/top_k_20_k_neighbors_15_n_tokens_0.5_MNT_300_test_size_0.2_reph_False_2025-11-22_00-08/all_experiment_results.json
81,n_tokens,0.1,81,comprehensive_results/subset_size-1000/2025-11-22_01-59/top_k_20_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_01-59/all_experiment_results.json
82,n_tokens,0.2,82,comprehensive_results/subset_size-1000/2025-11-22_02-00/top_k_20_k_neighbors_20_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_02-00/all_experiment_results.json
83,n_tokens,0.3,83,comprehensive_results/subset_size-1000/2025-11-22_02-07/top_k_20_k_neighbors_25_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_02-07/all_experiment_results.json
84,n_tokens,0.4,84,comprehensive_results/subset_size-1000/2025-11-22_02-13/top_k_20_k_neighbors_30_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_02-13/all_experiment_results.json
85,n_tokens,0.5,85,comprehensive_results/subset_size-1000/2025-11-22_03-36/top_k_1_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_03-36/all_experiment_results.json
86,n_tokens,0.6,86,comprehensive_results/subset_size-1000/2025-11-22_02-14/top_k_20_k_neighbors_40_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_02-14/all_experiment_results.json
87,n_tokens,0.7,87,comprehensive_results/subset_size-1000/2025-11-22_02-15/top_k_20_k_neighbors_15_n_tokens_0.1_MNT_300_test_size_0.2_reph_False_2025-11-22_02-15/all_experiment_results.json
88,n_tokens,0.8,88,comprehensive_results/subset_size-1000/2025-11-22_02-21/top_k_20_k_neighbors_15_n_tokens_0.2_MNT_300_test_size_0.2_reph_False_2025-11-22_02-21/all_experiment_results.json

In [8]:
# Export results_df to a JSON file
# Read mapping
output_file_name = os.path.join('results_file_mapping', f'{job_id}.json')
results_df.to_json(output_file_name, orient='records', indent=4)