In [12]:
# n_tokens = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
# max_gen_tokens = [100, 200, 400, 600]
# neighbor_dist = [1, 2, 4, 8, 16, 20, 25, 32, 42, 52, 64, 70]
# subset_size = [50, 100, 200, 400, 500, 800, 1000]
# max_neighbors = [5, 10, 15, 20, 25, 30, 40]

n_tokens = [0.45, 0.55]
neighbor_dist = [12, 14,
                 17, 18, 19,
                #  20
                 21, 22, 23, 24,
                #  25
                 26, 27, 28, 29, 30, 31]
max_neighbors = [5, 10, 15, 20, 25, 30, 40]
max_gen_tokens = [100, 200, 400, 600]
subset_size = [50, 100, 200, 400, 500, 800, 1000]

exps = ['n_tokens', 'neighbor_dist', 'max_neighbors'] # max_neighbors, max_gen_tokens, subset_size]
exps = {exp: eval(exp) for exp in exps}

results_files = {}

In [13]:
import os
import re
import glob
import pandas as pd

# Directory paths
job_id = '67903336'
terminal_runs_dir = f'/home/liranc6/W25/adversarial-attacks-on-deep-learning/project/terminal_runs/{job_id}'

# Build the experiment command mapping
exp_commands = []
for exp_name, values in exps.items():
    for value in values:
        exp_commands.append((exp_name, value))

# Repeat the pattern 4 times (indices 0-107)
exp_commands = exp_commands * 4

# Function to extract result file path from output file
def extract_result_path(output_file):
    """Extract the result file path from a terminal output file"""
    try:
        with open(output_file, 'r') as f:
            content = f.read()
            # Look for the JSON file path
            match = re.search(r'(comprehensive_results/subset_size-1000/[^\s]+/all_experiment_results\.json)', content)
            if match:
                return match.group(1)
    except Exception as e:
        print(f"Error reading {output_file}: {e}")
    return None

# Scrape all output files
output_files = sorted(glob.glob(f"{terminal_runs_dir}/out_job_*.txt"))

# Build the DataFrame
rows = []
for idx, output_file in enumerate(output_files):
    if idx >= len(exp_commands):
        break
    
    exp_name, exp_value = exp_commands[idx]
    result_path = extract_result_path(output_file)
    
    if result_path:
        rows.append({
            'parameter_name': exp_name,
            'val': exp_value,
            'job_idx': idx,
            'path_to_all_results': result_path
        })

# Create DataFrame
results_df = pd.DataFrame(rows)

# Set pandas to display full column width
pd.set_option('display.max_colwidth', None)

# Extract timestamp from path
results_df['timestamp'] = results_df['path_to_all_results'].apply(lambda x: x.split('/')[2])
# results_df['dir_path'] = results_df['path_to_all_results'].apply(lambda x: '/'.join(x.split('/')[:-1]))

print(f"Found {len(results_df)} results")
results_df

Found 96 results

,parameter_name,val,job_idx,path_to_all_results,timestamp
0,n_tokens,0.45,0,comprehensive_results/subset_size-1000/2025-11-20_11-14/top_k_20_k_neighbors_15_n_tokens_0.1_MNT_300_test_size_0.2_reph_False_2025-11-20_11-14/all_experiment_results.json,2025-11-20_11-14
1,n_tokens,0.55,1,comprehensive_results/subset_size-1000/2025-11-20_11-14/top_k_20_k_neighbors_15_n_tokens_0.2_MNT_300_test_size_0.2_reph_False_2025-11-20_11-14/all_experiment_results.json,2025-11-20_11-14
2,neighbor_dist,12.00,2,comprehensive_results/subset_size-1000/2025-11-20_21-50/top_k_4_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-20_21-50/all_experiment_results.json,2025-11-20_21-50
3,neighbor_dist,14.00,3,comprehensive_results/subset_size-1000/2025-11-22_03-17/top_k_70_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_03-17/all_experiment_results.json,2025-11-22_03-17
4,neighbor_dist,17.00,4,comprehensive_results/subset_size-1000/2025-11-22_03-23/top_k_20_k_neighbors_5_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_03-23/all_experiment_results.json,2025-11-22_03-23
...,...,...,...,...,...
91,max_neighbors,15.00,91,comprehensive_results/subset_size-1000/2025-11-22_02-32/top_k_20_k_neighbors_15_n_tokens_0.5_MNT_300_test_size_0.2_reph_False_2025-11-22_02-32/all_experiment_results.json,2025-11-22_02-32
92,max_neighbors,20.00,92,comprehensive_results/subset_size-1000/2025-11-22_02-34/top_k_20_k_neighbors_15_n_tokens_0.6_MNT_300_test_size_0.2_reph_False_2025-11-22_02-34/all_experiment_results.json,2025-11-22_02-34
93,max_neighbors,25.00,93,comprehensive_results/subset_size-1000/2025-11-22_02-36/top_k_20_k_neighbors_15_n_tokens_0.7_MNT_300_test_size_0.2_reph_False_2025-11-22_02-36/all_experiment_results.json,2025-11-22_02-36
94,max_neighbors,30.00,94,comprehensive_results/subset_size-1000/2025-11-22_02-36/top_k_20_k_neighbors_15_n_tokens_0.8_MNT_300_test_size_0.2_reph_False_2025-11-22_02-36/all_experiment_results.json,2025-11-22_02-36
95,max_neighbors,40.00,95,comprehensive_results/subset_size-1000/2025-11-22_02-42/top_k_1_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_02-42/all_experiment_results.json,2025-11-22_02-42

In [14]:
# Access specific experiments using query
# Example: results_df[results_df['parameter_name'] == 'n_tokens']
results_df[results_df['parameter_name'] == 'n_tokens']

,parameter_name,val,job_idx,path_to_all_results,timestamp
0,n_tokens,0.45,0,comprehensive_results/subset_size-1000/2025-11-20_11-14/top_k_20_k_neighbors_15_n_tokens_0.1_MNT_300_test_size_0.2_reph_False_2025-11-20_11-14/all_experiment_results.json,2025-11-20_11-14
1,n_tokens,0.55,1,comprehensive_results/subset_size-1000/2025-11-20_11-14/top_k_20_k_neighbors_15_n_tokens_0.2_MNT_300_test_size_0.2_reph_False_2025-11-20_11-14/all_experiment_results.json,2025-11-20_11-14
24,n_tokens,0.45,24,comprehensive_results/subset_size-1000/2025-11-21_09-22/top_k_20_k_neighbors_25_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-21_09-22/all_experiment_results.json,2025-11-21_09-22
25,n_tokens,0.55,25,comprehensive_results/subset_size-1000/2025-11-21_10-58/top_k_20_k_neighbors_30_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-21_10-58/all_experiment_results.json,2025-11-21_10-58
48,n_tokens,0.45,48,comprehensive_results/subset_size-1000/2025-11-21_22-37/top_k_70_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-21_22-37/all_experiment_results.json,2025-11-21_22-37
49,n_tokens,0.55,49,comprehensive_results/subset_size-1000/2025-11-21_22-40/top_k_20_k_neighbors_5_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-21_22-40/all_experiment_results.json,2025-11-21_22-40
72,n_tokens,0.45,72,comprehensive_results/subset_size-1000/2025-11-22_01-28/top_k_25_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_01-28/all_experiment_results.json,2025-11-22_01-28
73,n_tokens,0.55,73,comprehensive_results/subset_size-1000/2025-11-22_01-30/top_k_32_k_neighbors_15_n_tokens_0.3_MNT_300_test_size_0.2_reph_False_2025-11-22_01-30/all_experiment_results.json,2025-11-22_01-30

In [15]:
# Export results_df to a JSON file
# Read mapping
output_file_name = os.path.join('results_file_mapping', f'{job_id}.json')
results_df.to_json(output_file_name, orient='records', indent=4)